import { z } from "zod";
import { defineTool } from "@quickhelp/tool-kit";

const fileCoverageSchema = z.object({
  path: z.string(),
  linesCoverage: z.number().describe("Line coverage percentage 0–100"),
  functionsCoverage: z.number().describe("Function coverage percentage 0–100"),
  branchesCoverage: z.number().describe("Branch coverage percentage 0–100"),
  linesHit: z.number(),
  linesFound: z.number(),
  functionsHit: z.number(),
  functionsFound: z.number(),
  branchesHit: z.number(),
  branchesFound: z.number(),
});

function pct(hit: number, found: number): number {
  if (found === 0) return 100;
  return Math.round((hit / found) * 1000) / 10;
}

function parseLcov(content: string): z.infer<typeof fileCoverageSchema>[] {
  const files: z.infer<typeof fileCoverageSchema>[] = [];
  const records = content.split(/end_of_record/i);

  for (const record of records) {
    const trimmed = record.trim();
    if (!trimmed) continue;

    let path = "";
    let linesFound = 0, linesHit = 0;
    let functionsFound = 0, functionsHit = 0;
    let branchesFound = 0, branchesHit = 0;

    for (const line of trimmed.split(/\r?\n/)) {
      const colon = line.indexOf(":");
      if (colon === -1) continue;
      const key = line.slice(0, colon).trim();
      const value = line.slice(colon + 1).trim();

      switch (key) {
        case "SF": path = value; break;
        case "LF": linesFound = parseInt(value, 10) || 0; break;
        case "LH": linesHit = parseInt(value, 10) || 0; break;
        case "FNF": functionsFound = parseInt(value, 10) || 0; break;
        case "FNH": functionsHit = parseInt(value, 10) || 0; break;
        case "BRF": branchesFound = parseInt(value, 10) || 0; break;
        case "BRH": branchesHit = parseInt(value, 10) || 0; break;
      }
    }

    if (!path) continue;

    files.push({
      path,
      linesCoverage: pct(linesHit, linesFound),
      functionsCoverage: pct(functionsHit, functionsFound),
      branchesCoverage: pct(branchesHit, branchesFound),
      linesHit,
      linesFound,
      functionsHit,
      functionsFound,
      branchesHit,
      branchesFound,
    });
  }

  return files;
}

export const lcovViewer = defineTool({
  id: "lcov-viewer",
  slug: "lcov-viewer",
  name: "LCOV Coverage Viewer",
  summary: "Parse and visualize LCOV code coverage reports — line, function, and branch coverage per file.",
  description:
    "Paste or upload an LCOV .info file (generated by Jest, Istanbul/nyc, Vitest, gcov, coverage.py, and more) to get a structured coverage summary with per-file breakdown. All processing runs in your browser — your code never leaves your device.",
  category: "validation",
  inputSchema: z.object({
    lcov: z.string().describe("Raw LCOV .info file content"),
  }),
  outputSchema: z.object({
    summary: z.object({
      linesCoverage: z.number().describe("Overall line coverage 0–100"),
      functionsCoverage: z.number().describe("Overall function coverage 0–100"),
      branchesCoverage: z.number().describe("Overall branch coverage 0–100"),
      linesHit: z.number(),
      linesFound: z.number(),
      functionsHit: z.number(),
      functionsFound: z.number(),
      branchesHit: z.number(),
      branchesFound: z.number(),
    }),
    files: z.array(fileCoverageSchema),
  }),
  examples: [
    {
      title: "Parse a Jest LCOV report",
      input: {
        lcov: "TN:\nSF:src/utils.ts\nFNF:3\nFNH:2\nBRF:8\nBRH:6\nDA:1,1\nDA:2,1\nDA:3,0\nLF:3\nLH:2\nend_of_record",
      },
      output: {
        summary: {
          linesCoverage: 66.7,
          functionsCoverage: 66.7,
          branchesCoverage: 75.0,
          linesHit: 2,
          linesFound: 3,
          functionsHit: 2,
          functionsFound: 3,
          branchesHit: 6,
          branchesFound: 8,
        },
        files: [
          {
            path: "src/utils.ts",
            linesCoverage: 66.7,
            functionsCoverage: 66.7,
            branchesCoverage: 75.0,
            linesHit: 2,
            linesFound: 3,
            functionsHit: 2,
            functionsFound: 3,
            branchesHit: 6,
            branchesFound: 8,
          },
        ],
      },
    },
  ],
  handler({ lcov }) {
    const files = parseLcov(lcov);

    const totals = files.reduce(
      (acc, f) => ({
        linesHit: acc.linesHit + f.linesHit,
        linesFound: acc.linesFound + f.linesFound,
        functionsHit: acc.functionsHit + f.functionsHit,
        functionsFound: acc.functionsFound + f.functionsFound,
        branchesHit: acc.branchesHit + f.branchesHit,
        branchesFound: acc.branchesFound + f.branchesFound,
      }),
      { linesHit: 0, linesFound: 0, functionsHit: 0, functionsFound: 0, branchesHit: 0, branchesFound: 0 }
    );

    return {
      summary: {
        linesCoverage: pct(totals.linesHit, totals.linesFound),
        functionsCoverage: pct(totals.functionsHit, totals.functionsFound),
        branchesCoverage: pct(totals.branchesHit, totals.branchesFound),
        ...totals,
      },
      files,
    };
  },
  schemaOrg: {
    name: "LCOV Coverage Viewer",
    description:
      "Free online LCOV coverage report viewer. Parse .info files from Jest, Istanbul, gcov, Vitest, and coverage.py to see line, function, and branch coverage.",
    url: "https://quickhelp.dev/lcov-viewer",
  },
  attribution: {
    text: "Processed by quickhelp.dev/lcov-viewer",
    url: "https://quickhelp.dev/lcov-viewer",
  },
  content: {
    whatIs:
      "LCOV Coverage Viewer is a free online tool that parses LCOV .info files and displays a human-readable coverage report. LCOV is the standard output format for code coverage tools across many languages and test runners — including Jest (JavaScript), Istanbul/nyc (JavaScript), Vitest (TypeScript), gcov (C/C++), and coverage.py (Python). An LCOV .info file encodes line-by-line, function-by-function, and branch-by-branch execution data for every source file in your project. This tool reads that data and renders it as a sortable, filterable table showing which files are well-covered and which need more tests. Processing is entirely client-side — your source code and coverage data never leave your browser.",
    howToSteps: [
      {
        name: "Generate your LCOV report",
        text: "Run your test suite with coverage enabled. For Jest: add --coverage and set coverageReporters: ['lcov'] in jest.config. For Vitest: set coverage.reporter: ['lcov']. For Python: run coverage run then coverage lcov. The output is a file called lcov.info or coverage/lcov.info.",
      },
      {
        name: "Upload or paste the .info file",
        text: "Drag your lcov.info file onto the upload area, or paste its raw text content into the input field. The viewer accepts any standard LCOV format regardless of which tool generated it.",
      },
      {
        name: "Inspect coverage by file",
        text: "The summary cards show overall line, function, and branch coverage percentages. The file table lists every source file with its individual coverage and colored indicators — green (≥80%), yellow (60–80%), and red (<60%). Sort any column or search by filename to find the biggest coverage gaps.",
      },
    ],
    faq: [
      {
        question: "Is my code or coverage data sent to a server?",
        answer:
          "No. The LCOV parser runs entirely in your browser in JavaScript. Your .info file is never uploaded — it is read and parsed locally. This makes the tool safe for proprietary codebases.",
      },
      {
        question: "Which test runners and coverage tools produce LCOV output?",
        answer:
          "Jest (coverageReporters: ['lcov']), Vitest (coverage.reporter: ['lcov']), Istanbul/nyc (--reporter=lcov), gcov (with lcov CLI), coverage.py (coverage lcov), Cargo/tarpaulin (--out Lcov), and most CI coverage platforms including Codecov and Coveralls.",
      },
      {
        question: "What is the difference between line, function, and branch coverage?",
        answer:
          "Line coverage counts whether each executable line was reached by at least one test. Function coverage counts whether each function was called. Branch coverage counts both sides of every conditional (if/else, ternary, switch) — a line with a conditional shows as covered even if only one branch was taken.",
      },
    ],
    relatedTools: ["json-formatter"],
    useCases: [
      {
        slug: "view-jest-lcov-coverage-report",
        title: "How to view a Jest LCOV coverage report online",
        intent: "Inspect Jest test coverage results from a lcov.info file without installing a local HTML viewer.",
        intro: "Jest generates an LCOV report at coverage/lcov.info when you run tests with --coverage and have 'lcov' in your coverageReporters list. The built-in HTML report requires a local browser and is lost after CI runs. This guide shows how to view that report online using the quickhelp.dev LCOV Coverage Viewer — paste or upload the file and immediately see which files have low coverage, sortable by percentage. No install, no sign-up, runs entirely in your browser.",
        steps: [
          { name: "Run Jest with LCOV output", text: "In your jest.config.js, set coverageReporters: ['lcov', 'text'] and run npx jest --coverage. The file coverage/lcov.info is created in your project root." },
          { name: "Upload to the viewer", text: "Open quickhelp.dev/lcov-viewer and drag coverage/lcov.info onto the upload area. The file is parsed instantly in your browser." },
          { name: "Find uncovered files", text: "The file table lists every source file. Sort by Line Coverage ascending to see the worst-covered files first. Red bars highlight files below 60% coverage." },
        ],
        faq: [
          { question: "How do I enable LCOV output in Jest?", answer: "Add coverageReporters: ['lcov'] to your jest.config.js, or pass --coverageReporters=lcov on the command line. Run jest --coverage to generate the report." },
          { question: "Can I view coverage from a CI run?", answer: "Yes — download the coverage/lcov.info artifact from your CI pipeline (GitHub Actions, GitLab CI, etc.) and upload it to the viewer." },
        ],
      },
      {
        slug: "view-istanbul-nyc-coverage-report",
        title: "How to view an Istanbul/nyc coverage report online",
        intent: "Parse an LCOV .info file from Istanbul or nyc to visualize JavaScript coverage without serving HTML files.",
        intro: "Istanbul (via the nyc command) is the standard JavaScript coverage tool for Mocha, Tap, and other non-Jest test runners. Running nyc --reporter=lcov generates a coverage/lcov.info file. The HTML report requires a local server and is often omitted in CI. This guide shows how to upload the LCOV output from nyc to the quickhelp.dev Coverage Viewer and read file-level coverage instantly.",
        steps: [
          { name: "Run your tests through nyc", text: "Prefix your test command: nyc --reporter=lcov mocha tests/**/*.spec.js. The coverage directory is created with lcov.info inside." },
          { name: "Open the viewer and upload", text: "Go to quickhelp.dev/lcov-viewer, drag the lcov.info file onto the page. All source files appear in the table immediately." },
          { name: "Identify coverage gaps", text: "Use the sort controls to rank files by line coverage. Files with branch coverage below function coverage often have untested else branches in conditionals." },
        ],
        faq: [
          { question: "Does this work with c8 (V8 native coverage)?", answer: "Yes — c8 can output LCOV format with --reporter=lcov. The resulting lcov.info file is compatible with this viewer." },
          { question: "Why is branch coverage lower than line coverage?", answer: "A line with a conditional is counted as covered when any branch is taken. Branch coverage counts each branch separately, so an untested else path lowers branch coverage even if the line was reached." },
        ],
      },
      {
        slug: "check-python-coverage-with-lcov",
        title: "How to view Python coverage.py reports as LCOV",
        intent: "Convert a Python coverage.py report to LCOV format and view it online.",
        intro: "Python's coverage.py tool can export reports in LCOV format since version 6.3. This lets you view Python coverage data in the same tools used for JavaScript and C++ projects. This guide explains how to generate the LCOV file from a Python project using pytest-cov or coverage.py, then view it without installing any additional software.",
        steps: [
          { name: "Run pytest with LCOV output", text: "Install pytest-cov and run: pytest --cov=src --cov-report=lcov:coverage.lcov. The file coverage.lcov is created in your project root." },
          { name: "Upload the .lcov file", text: "Open quickhelp.dev/lcov-viewer and upload coverage.lcov. The viewer accepts both .info and .lcov file extensions — they use the same format." },
          { name: "Read coverage by module", text: "Python module paths (e.g., src/auth/tokens.py) appear in the file table. Low-coverage modules show red or yellow indicators — sort by coverage to prioritize test writing." },
        ],
        faq: [
          { question: "Does coverage.py support LCOV output natively?", answer: "Yes, since version 6.3. Run coverage lcov -o coverage.lcov after coverage run. Or configure it in .coveragerc: [report] format = lcov." },
          { question: "What if my .lcov file is very large?", answer: "The viewer processes files entirely in JavaScript in your browser. Files up to a few megabytes parse quickly. For extremely large monorepo reports, parsing may take a few seconds." },
        ],
      },
      {
        slug: "analyze-vitest-coverage-report",
        title: "How to analyze a Vitest coverage report with LCOV",
        intent: "View Vitest test coverage from a lcov.info file to identify under-tested TypeScript files.",
        intro: "Vitest's built-in coverage (via @vitest/coverage-v8 or @vitest/coverage-istanbul) can generate LCOV output alongside its terminal summary. The LCOV file gives you per-file detail that the terminal summary omits. This guide shows how to configure Vitest to emit LCOV and how to view the results using the quickhelp.dev LCOV Coverage Viewer.",
        steps: [
          { name: "Configure Vitest LCOV reporter", text: "In vitest.config.ts, set: coverage: { reporter: ['lcov', 'text'], reportsDirectory: 'coverage' }. Run vitest --coverage." },
          { name: "Upload lcov.info", text: "Find coverage/lcov.info in your project. Upload it to quickhelp.dev/lcov-viewer. All TypeScript source files appear with their coverage percentages." },
          { name: "Prioritize test writing", text: "Sort by branch coverage ascending to find the most under-tested files. Branch coverage reveals missing test cases for conditional logic better than line coverage alone." },
        ],
        faq: [
          { question: "Should I use @vitest/coverage-v8 or coverage-istanbul?", answer: "V8 coverage uses the JavaScript engine's native instrumentation and is faster but less precise. Istanbul instruments your source code for more accurate branch data. For TypeScript projects, istanbul usually gives more meaningful branch coverage numbers." },
          { question: "Can I fail CI when coverage drops below a threshold?", answer: "Yes — use the API endpoint (POST /api/lcov-viewer) in your CI pipeline to parse lcov.info and extract the summary JSON, then assert on linesCoverage, functionsCoverage, or branchesCoverage." },
        ],
      },
      {
        slug: "view-github-actions-coverage-artifact",
        title: "How to view a coverage report from GitHub Actions",
        intent: "Download and inspect the LCOV coverage artifact from a GitHub Actions workflow run.",
        intro: "GitHub Actions workflows generate coverage reports as downloadable artifacts. When your CI uploads a lcov.info file, you can download it and view the per-file breakdown without checking out the branch or running the tests locally — useful for reviewing coverage on a colleague's pull request.",
        steps: [
          { name: "Download the coverage artifact", text: "In GitHub, open the Actions tab, click the workflow run, scroll to Artifacts, and download the coverage artifact. Extract the zip to find lcov.info." },
          { name: "Upload to the LCOV viewer", text: "Drag the lcov.info file onto quickhelp.dev/lcov-viewer. Coverage data appears within seconds — no local test run needed." },
          { name: "Review PR coverage gaps", text: "Compare the file list against the changed files in the PR. Files changed in the PR that appear red or yellow in the viewer are the ones that need more test coverage." },
        ],
        faq: [
          { question: "How do I add LCOV artifact upload to my GitHub Actions workflow?", answer: "Add this step after your test command: uses: actions/upload-artifact@v4 with name: coverage, path: coverage/lcov.info. This makes the file downloadable from the Actions UI." },
          { question: "Can I compare coverage between two branches?", answer: "Download the lcov.info artifact from each branch's latest CI run and open them in separate browser tabs. The viewer shows one report at a time." },
        ],
      },
      {
        slug: "read-lcov-info-file-format",
        title: "How to read and understand an LCOV .info file",
        intent: "Understand the LCOV .info file format to debug coverage data or write a custom parser.",
        intro: "An LCOV .info file is a plain-text format where each record describes coverage for one source file. Understanding the format helps when debugging why coverage numbers look wrong, when writing a custom parser, or when comparing coverage data between tools. This guide explains every field in the LCOV format and shows how to read a real .info file. The quickhelp.dev LCOV Coverage Viewer can validate that your file is well-formed.",
        steps: [
          { name: "Understand the record structure", text: "Each file's data starts with SF:<path> and ends with end_of_record. Fields DA:<line>,<hit-count> record each executable line, FN/<FNDA for functions, and BRDA for branches." },
          { name: "Read the summary fields", text: "LF (lines found) and LH (lines hit) give the file totals. Coverage % = LH/LF × 100. FNF/FNH are function totals; BRF/BRH are branch totals." },
          { name: "Validate your file", text: "Upload your .info file to quickhelp.dev/lcov-viewer. If the viewer shows no data, check that each record ends with end_of_record and that SF: lines use valid paths." },
        ],
        faq: [
          { question: "What does DA:5,0 mean in an LCOV file?", answer: "DA stands for Data. DA:5,0 means line 5 of the source file was never executed (0 hits). DA:5,3 means line 5 was executed 3 times during the test run." },
          { question: "What is the TN: field?", answer: "TN (Test Name) is an optional test identifier at the start of a record. Most tools leave it empty (TN:). It has no effect on coverage calculation and is ignored by most viewers." },
        ],
      },
    ],
  },
});
