import { randomUUID } from "crypto";
import { z } from "zod";
import { defineTool } from "@quickhelp/tool-kit";

export const uuidGenerator = defineTool({
  id: "uuid-generator",
  slug: "uuid-generator",
  name: "UUID Generator",
  summary: "Generate one or more cryptographically random UUID v4 identifiers instantly.",
  description:
    "Generate cryptographically random UUID version 4 identifiers (RFC 4122) using the Node.js crypto module. Produces between 1 and 100 UUIDs per request, in standard hyphenated format or compact (no hyphens). Also validates whether a given string is a valid UUID.",
  category: "generation",
  inputSchema: z.object({
    count: z
      .number()
      .int()
      .min(1)
      .max(100)
      .default(1)
      .describe("Number of UUIDs to generate (1–100)"),
    format: z
      .enum(["hyphenated", "compact"])
      .default("hyphenated")
      .describe(
        "hyphenated — standard xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx format; compact — 32 hex characters with no hyphens"
      ),
    validate: z
      .string()
      .optional()
      .describe(
        "If provided, validate this string as a UUID instead of generating new ones. Returns is_valid and the detected version."
      ),
  }),
  outputSchema: z.object({
    uuids: z.array(z.string()).describe("Generated UUID(s)"),
    count: z.number().int(),
    format: z.enum(["hyphenated", "compact"]),
    is_valid: z.boolean().optional().describe("Set when 'validate' input is provided"),
    validated_version: z.string().optional().describe("UUID version detected during validation (e.g. 'v4')"),
  }),
  examples: [
    {
      title: "Generate one UUID v4",
      input: { count: 1, format: "hyphenated" },
      output: {
        uuids: ["550e8400-e29b-41d4-a716-446655440000"],
        count: 1,
        format: "hyphenated",
      },
    },
    {
      title: "Generate 5 compact UUIDs",
      input: { count: 5, format: "compact" },
      output: {
        uuids: [
          "550e8400e29b41d4a716446655440000",
          "6ba7b810e29b11d1a71600c04fd430c8",
          "6ba7b811e29b11d1a71600c04fd430c8",
          "6ba7b812e29b11d1a71600c04fd430c8",
          "6ba7b814e29b11d1a71600c04fd430c8",
        ],
        count: 5,
        format: "compact",
      },
    },
    {
      title: "Validate a UUID",
      input: { count: 1, format: "hyphenated", validate: "550e8400-e29b-41d4-a716-446655440000" },
      output: {
        uuids: [],
        count: 0,
        format: "hyphenated",
        is_valid: true,
        validated_version: "v4",
      },
    },
  ],
  handler({ count, format, validate }) {
    // Validation mode
    if (validate !== undefined) {
      const hyphenated = /^[0-9a-f]{8}-[0-9a-f]{4}-([1-5])[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
      const compact = /^[0-9a-f]{8}([0-9a-f]{4})([1-5][0-9a-f]{3})([89ab][0-9a-f]{3})([0-9a-f]{12})$/i;
      const trimmed = validate.trim();
      const hMatch = trimmed.match(hyphenated);
      const cMatch = !hMatch && trimmed.match(compact);
      const versionDigit = hMatch ? hMatch[1] : cMatch ? cMatch[1] : null;
      const is_valid = !!(hMatch || cMatch);
      return {
        uuids: [],
        count: 0,
        format,
        is_valid,
        validated_version: versionDigit ? `v${versionDigit}` : undefined,
      };
    }

    // Generation mode
    const uuids: string[] = [];
    for (let i = 0; i < count; i++) {
      const raw = randomUUID(); // always hyphenated v4
      uuids.push(format === "compact" ? raw.replace(/-/g, "") : raw);
    }
    return { uuids, count, format };
  },
  schemaOrg: {
    name: "UUID Generator",
    description:
      "Generate cryptographically random UUID v4 identifiers, in standard or compact format.",
    url: "https://quickhelp.dev/uuid-generator",
  },
  attribution: {
    text: "Generated by quickhelp.dev/uuid-generator",
    url: "https://quickhelp.dev/uuid-generator",
  },
  content: {
    whatIs:
      "A UUID (Universally Unique Identifier) is a 128-bit identifier standardised in RFC 4122 and represented as 32 hexadecimal digits in the pattern xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. UUID version 4 — the most common variant — fills all bits with cryptographically random data, making collisions statistically impossible: with 1 trillion UUIDs generated per second it would take approximately 85 years before a 50% chance of a single collision occurs. UUIDs are used as primary keys in databases, correlation IDs in distributed logs, session tokens, file names, API resource identifiers, and idempotency keys in payment systems. Because they are generated client-side without a central registry, distributed systems can create UUIDs in parallel without coordination. The compact format (no hyphens) saves 4 characters and is commonly used in URLs and file names.",
    howToSteps: [
      {
        name: "Choose how many UUIDs you need",
        text: "Set the count to 1 for a single identifier or up to 100 for a bulk batch — useful when pre-generating IDs for a database seed script or test fixture.",
      },
      {
        name: "Choose a format",
        text: "Hyphenated format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) is the RFC 4122 standard and is accepted by most databases and ORMs. Compact format (no hyphens, 32 hex chars) is smaller and safe for URLs, file names, and systems that require alphanumeric-only keys.",
      },
      {
        name: "Copy and use",
        text: "Click Copy to put all generated UUIDs on your clipboard — one per line for multi-UUID batches. To validate an existing UUID, paste it into the 'validate' field and the tool reports whether it matches the UUID format and which version it is.",
      },
    ],
    faq: [
      {
        question: "Are UUID v4 values truly random and safe to use as primary keys?",
        answer:
          "Yes. UUID v4 uses a cryptographically secure random number generator (Node.js crypto.randomUUID(), which calls the OS CSPRNG). Two independently generated v4 UUIDs colliding is astronomically unlikely — roughly a 1 in 5.3×10³⁶ chance per pair. They are safe as primary keys in databases, session tokens, and correlation IDs.",
      },
      {
        question: "What is the difference between UUID v1, v4, and v7?",
        answer:
          "v1 encodes the MAC address and timestamp — sortable but exposes hardware identity. v4 is fully random — the most privacy-safe and widely supported. v7 (RFC 9562, 2024) encodes a millisecond-precision timestamp in the high bits so UUIDs sort chronologically, which improves database index locality. This tool generates v4. For v7, use a dedicated library like 'uuid' on npm.",
      },
      {
        question: "Can I use a UUID without the hyphens?",
        answer:
          "Yes. Hyphens are part of the canonical textual representation but carry no information — the 128-bit value is identical. The compact format (32 hex chars, no hyphens) is common in URLs, file names, and storage systems that require alphanumeric-only identifiers. Most UUID parsers accept both formats.",
      },
    ],
    relatedTools: ["hash-generator", "timestamp-converter"],
    useCases: [
      {
        slug: "generate-uuid-v4-online",
        title: "How to generate a UUID v4 online",
        intent: "Get a cryptographically random UUID instantly without installing any tools.",
        intro:
          "UUID v4 is the default choice for generating unique identifiers in web applications, databases, and APIs. Whether you need a one-off ID for a test fixture, a correlation ID to paste into a log query, or a batch of IDs for a database seed script, this tool generates them in milliseconds without installing Node.js, Python, or any CLI tools. This guide shows how to generate one or more UUID v4 values and choose the right format for your use case.",
        steps: [
          {
            name: "Set the count",
            text: "For a single ID, leave count at 1. For a batch — database seeds, test fixtures, bulk inserts — set count up to 100. Each UUID is independently random.",
          },
          {
            name: "Choose hyphenated or compact",
            text: "Use hyphenated (the default) for SQL columns typed as UUID, for ORM models, and anywhere the RFC 4122 format is expected. Use compact for URLs, file names, or systems that reject hyphens.",
          },
          {
            name: "Click Generate and copy",
            text: "The UUIDs appear instantly. Click Copy to put them on your clipboard — one per line for multi-UUID batches, ready to paste into SQL, JSON, or a spreadsheet.",
          },
        ],
        faq: [
          {
            question: "Is it safe to use a UUID generated in a web tool?",
            answer:
              "Yes — this tool generates UUIDs server-side using Node.js crypto.randomUUID(), which calls the OS cryptographically secure random number generator. The generated values are never stored or logged. For extremely sensitive secrets (tokens, passwords), use a dedicated secret manager rather than a UUID.",
          },
          {
            question: "Can I use these UUIDs as database primary keys?",
            answer:
              "Yes, UUID v4 is widely used as a primary key in PostgreSQL (uuid type), MySQL (CHAR(36) or BINARY(16)), MongoDB, and most modern ORMs. Note that random UUIDs cause index fragmentation over time in clustered indexes. If you insert millions of rows per day, consider UUID v7 (time-ordered) or ULID instead.",
          },
        ],
      },
      {
        slug: "validate-uuid-format",
        title: "How to validate whether a string is a valid UUID",
        intent: "Check if an ID from an API response or user input matches the UUID format.",
        intro:
          "APIs, databases, and user inputs sometimes pass values that are supposed to be UUIDs but contain typos, extra characters, or wrong formats. Validating the format before processing the ID prevents confusing downstream errors. This guide shows how to check any string against the UUID v1–v5 format and identify the version.",
        steps: [
          {
            name: "Copy the string to validate",
            text: "Copy the identifier from the API response, URL parameter, database field, or user input you want to check.",
          },
          {
            name: "Paste into the validate field",
            text: "Paste the string into the 'validate' input of the UUID Generator. The tool checks it against the RFC 4122 regex for versions 1–5 and reports is_valid: true or false.",
          },
          {
            name: "Read the version",
            text: "The validated_version field shows which UUID version the string is (v1–v5). If is_valid is false, the string is not a UUID — check for missing hyphens, wrong length, or non-hex characters.",
          },
        ],
        faq: [
          {
            question: "Does the validator check the UUID content, or just the format?",
            answer:
              "Format only. Validation confirms the string matches the 8-4-4-4-12 hex pattern with a valid version digit (1–5) and variant bits. It cannot confirm that the UUID was actually generated by a trusted source — for that, you need a token or signature scheme.",
          },
          {
            question: "What if my UUID is in compact format (no hyphens)?",
            answer:
              "The validator accepts both hyphenated and compact (32 hex chars, no hyphens) formats. Compact UUIDs are checked by inserting the hyphens at the correct positions before pattern matching.",
          },
        ],
      },
      {
        slug: "uuid-vs-auto-increment",
        title: "How to choose between UUID and auto-increment IDs",
        intent: "Decide when to use UUID primary keys vs sequential integer IDs in a database.",
        intro:
          "Choosing between UUID and auto-increment integer IDs is one of the most common database design decisions. UUIDs are globally unique and can be generated client-side without a round-trip to the database; integers are compact, cache-friendly, and sort naturally. The right answer depends on your data volume, distribution model, and privacy requirements. This guide explains the trade-offs so you can make the right choice before your schema is in production.",
        steps: [
          {
            name: "Choose UUID when you need global uniqueness or client-side generation",
            text: "If your system is distributed (multiple writers, microservices, multi-tenant), or if clients generate IDs before writing to the server, use UUID v4. You can generate thousands of IDs without a database round-trip and merge data from different sources without conflicts.",
          },
          {
            name: "Choose auto-increment when you need compact, sortable keys",
            text: "Integer IDs are 4–8 bytes vs 16 bytes for UUID, sort by insertion order, and perform better in clustered indexes (B-tree pages stay ordered). Use them for high-volume tables where index fragmentation is a concern.",
          },
          {
            name: "Use UUID v7 as a middle ground",
            text: "UUID v7 (RFC 9562) encodes a millisecond timestamp in the high bits, making UUIDs sort chronologically. This gives you global uniqueness and client-side generation while preserving B-tree index locality. Generate a test UUID v7 with: const { v7: uuidv7 } = require('uuid'); console.log(uuidv7());",
          },
        ],
        faq: [
          {
            question: "Can I expose UUID primary keys in URLs?",
            answer:
              "Yes, and this is a common reason to prefer UUIDs over integers — integers in URLs reveal record counts and make sequential enumeration attacks trivial. A UUID in a URL (/orders/550e8400-e29b-41d4-a716-446655440000) reveals nothing about the total number of records.",
          },
          {
            question: "How much storage does a UUID use vs an integer?",
            answer:
              "A UUID stored as BINARY(16) uses 16 bytes. A BIGINT uses 8 bytes. Stored as CHAR(36) with hyphens it uses 36 bytes. For large tables, the storage difference compounds in every index that includes the primary key. Use BINARY(16) if storage is a concern.",
          },
        ],
      },
      {
        slug: "uuid-as-idempotency-key",
        title: "How to use a UUID as an idempotency key",
        intent: "Generate a UUID to use as an idempotency key for safe API request retries.",
        intro:
          "Payment APIs, message queues, and distributed systems use idempotency keys to prevent duplicate operations when retries occur. The key must be unique per logical operation and stable across retries of the same operation. UUID v4 is the standard choice: it is random enough to be unique, has no semantic meaning that could change, and is supported by Stripe, Adyen, and most major APIs as the expected format. This guide shows how to generate and use a UUID idempotency key.",
        steps: [
          {
            name: "Generate a UUID for the operation",
            text: "Generate one UUID here before making the API call. Store it alongside the pending operation in your database or in-memory state. This UUID is the idempotency key — the same key must be sent on every retry of the same logical request.",
          },
          {
            name: "Include it in the API request header",
            text: "For Stripe: add the header Idempotency-Key: <uuid>. For other APIs, check the documentation — common header names are X-Idempotency-Key, X-Request-ID, or Idempotency-Key. Pass the same UUID on every retry.",
          },
          {
            name: "Discard it after success",
            text: "Once the operation succeeds (HTTP 200/201), the idempotency key has served its purpose. Generate a fresh UUID for the next distinct operation — never reuse a key across different logical operations.",
          },
        ],
        faq: [
          {
            question: "How long should I keep the idempotency key?",
            answer:
              "Keep it for at least as long as you might retry the operation — typically 24–72 hours. Most payment APIs retain idempotency keys for 24 hours on their side. After that window, sending the same key may be treated as a new request.",
          },
          {
            question: "Can I use any random string as an idempotency key, or does it have to be a UUID?",
            answer:
              "Most APIs accept any unique string up to a length limit (typically 255 characters). UUID is the conventional choice because it is universally unique and the format is well understood. Avoid timestamps or sequential integers — they are not unique enough under concurrent retries.",
          },
        ],
      },
    ],
  },
});
